Global:
  use_gpu: true
  epoch_num: 4
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: ./output/ch_db_mbv3/
  save_epoch_step: 100
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [100, 1000, 2000]
  cal_metric_during_train: False
  pretrained_model: ./inference/ch_ppocr_server_v2.0_det_train/best_accuracy
  checkpoints: ./weights/ch_ppocr_mobile_v2.0_det_train.pt
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt
  device: cuda:0
  image_shape: [3, 320, 320]
  test_path: ./samples/1.jpg

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: True
  Neck:
    name: DBFPN
    out_channels: 96
  Head:
    name: DBHead
    k: 50

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.5
  max_candidates: 1000
  unclip_ratio: 1.5

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  betas: [0.9, 0.99]
  lr:  0.001
#    name: Cosine
#    learning_rate: 0.001
#    warmup_epoch: 2
#  regularizer:
#    name: 'L2'
#    factor: 0

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/tjm/Documents/python/pycharmProjects/PaddleOCR/train_data/tianchi
    label_file_list:
      - /home/tjm/Documents/python/pycharmProjects/PaddleOCR/train_data/tianchi/train_list.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - {'type': Fliplr, 'args': {'p': 0.5}}
            - {'type': Affine, 'args': {'rotate': [-10, 10]}}
            - {'type': Resize, 'args': {'size': [0.5, 3]}}
      - EastRandomCropData:
          size: [960, 960]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    pin_memory: True
    drop_last: False
    batch_size: 16
    num_workers: 6

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2